### ISSUE TITLE
MI 8 android 10 监听截屏图片文件路径没有监听到文件变化并回调FileObserverEvent方法

### ISSUE THREAD

**Issue by Dorsey-C** [jiangchaochao/fileObserver#1]
@Override
    public void onRequestPermissionsResult(int requestCode,
                                           @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == 100) {
            if (permissions.length == 2 && grantResults.length == 2) {
                if (grantResults[1] == PERMISSION_GRANTED
                        && grantResults[0] == PERMISSION_GRANTED) {
//                    String path = Environment.getExternalStorageDirectory().getAbsolutePath();
                    String path = Environment.getExternalStorageDirectory().getPath()+"/DCIM/Screenshots/";

                    FileObserverJni fileObserverJni = new FileObserverJni(path, FileObserverJni.ALL_EVENTS);
                    fileObserverJni.setmCallback(new FileObserverJni.Callback() {
                        @Override
                        public void FileObserverEvent(String path, int mask) {
                            Log.e(TAG, "FileObserverEvent: xxxxxxxxxxxxxx"+";path--->:"+path);
                            // 在这里监听事件
                            Toast.makeText(MainActivity.this,path,Toast.LENGTH_SHORT).show();
                        }
                    });
                }
            } else {
                Toast.makeText(this, "请允许读取图片信息权限", Toast.LENGTH_SHORT).show();
            }
        }
    }

**Comment by jiangchaochao** [comment]
@Dorsey-C  新版本添加了初始化回调接口，错误原因获取以及禁用了Android Q的分区存储，我测试了华为手机的Android10没发现问题，可以再测试一下
